In [3]:
! pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in c:\users\yifan ma\anaconda3\lib\site-packages (0.20.3)


In [2]:
! python -m pip install --upgrade pip

  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1


In [39]:
import numpy as np
#this is the example about similarity
dataset_filename = 'E:/My Learning/Learning data mining/LearningDataMiningwithPythonSecondEdition_Code/Chapter01/affinity_dataset.txt'
X = np.loadtxt(dataset_filename)

In [40]:
print(X[:5])

[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [41]:
X[0:3]

array([[0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.]])

In [42]:
#count the # of customers who bought apples
number_apple = 0
for sample_apple in X:
    if sample_apple[3] == 1:
        number_apple += 1
print(str(number_apple) + ' people bought apples.')

43 people bought apples.


In [43]:
#generate a default dictionary
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occurances = defaultdict(int)

In [44]:
#get the number of rows and columns
n_samples, n_features = X.shape
n_samples, n_features

(100, 5)

In [46]:
#check if sample customer bought product premise
for sample in X:
    for premise in range(5):
#if customer didn't buy this premise, skip to the next
        if sample[premise] == 0:
            continue
#if customer bought product premise, then add 1 occurance to product premise    
        else:
            num_occurances[premise] += 1
#exclude all the cases when product premise and product conclusion are the same
        for conclusion in range(n_features):
            if premise == conclusion:
                continue
            if sample[conclusion] == 1:
                valid_rules[(premise, conclusion)] += 1
            else:
                invalid_rules[(premise,conclusion)] += 1

In [48]:
#calculate the value of support and confidence
#support is based on number of cases matched valid rule
support = valid_rules

#confidence is based on ratio of valid number against number of occurances
confidence = defaultdict(float)
for premise, conclusion in valid_rules.keys():
    confidence[(premise,conclusion)] = valid_rules[(premise, conclusion)] / num_occurances[premise]

In [49]:
#define a function
#input: premise, conclusion, support dictionary, confidence dictionary, features
#output: support and confidence of each rule (the combination of premise and conclusion)
def rule_of_feature (premise, conclusion, support, confidence, features):
    premise_name = features[premise]
    conclusion_name = features[conclusion]
#change the index of a feature to a feature name
    print('if people buy {0} they will also buy {1}'.format(premise_name, conclusion_name))
    print(' - Support: {0}'.format(support[(premise,conclusion)]))
    print(' - Confidence: {0:.3f}'.format(confidence[(premise,conclusion)]))

In [66]:
features = ['bread','milk','cheese','apple','banana']
premise = 2
conclusion = 3
rule_of_feature(premise,conclusion,support,confidence,features)

if people buy cheese they will also buy apple
 - Support: 22
 - Confidence: 0.564


In [68]:
from operator import itemgetter
#display all the elements in the support dictionary
support.items()

dict_items([((0, 1), 13), ((1, 0), 13), ((2, 4), 20), ((4, 2), 20), ((2, 3), 22), ((3, 2), 22), ((3, 4), 27), ((4, 3), 27), ((1, 3), 18), ((3, 1), 18), ((1, 4), 27), ((4, 1), 27), ((0, 2), 5), ((2, 0), 5), ((0, 4), 16), ((4, 0), 16), ((1, 2), 11), ((2, 1), 11), ((0, 3), 9), ((3, 0), 9)])

In [74]:
#sort the list by descending support 
sorted_support = sorted(support.items(), key = itemgetter(1), reverse = True)
#display top 5 supports
sorted_support[0:5]

[((3, 4), 27), ((4, 3), 27), ((1, 4), 27), ((4, 1), 27), ((2, 3), 22)]

In [76]:
#display the top 5 support combinations of premise and conclusion
for id in range(5):
    print('Conclusion #{0}:'.format(id + 1))
    premise, conclusion = sorted_support[id][0]
    rule_of_feature(premise, conclusion, support, confidence,features)

Conclusion #1:
if people buy apple they will also buy banana
 - Support: 27
 - Confidence: 0.628
Conclusion #2:
if people buy banana they will also buy apple
 - Support: 27
 - Confidence: 0.474
Conclusion #3:
if people buy milk they will also buy banana
 - Support: 27
 - Confidence: 0.519
Conclusion #4:
if people buy banana they will also buy milk
 - Support: 27
 - Confidence: 0.474
Conclusion #5:
if people buy cheese they will also buy apple
 - Support: 22
 - Confidence: 0.564


In [92]:
#sort the list by descending confidence
sorted_confidence = sorted(confidence.items(), key = itemgetter(1), reverse = True)
#display top 5 confidence
sorted_confidence[0:5]

AttributeError: 'list' object has no attribute 'DESCR'

In [79]:
#display the top 5 conclusion combinations of premise and conclusion
for id in range(5):
    print('Conclusion #{0}:'.format(id + 1))
    premise, conclusion = sorted_confidence[id][0]
    rule_of_feature(premise, conclusion, support, confidence,features)

Conclusion #1:
if people buy apple they will also buy banana
 - Support: 27
 - Confidence: 0.628
Conclusion #2:
if people buy bread they will also buy banana
 - Support: 16
 - Confidence: 0.571
Conclusion #3:
if people buy cheese they will also buy apple
 - Support: 22
 - Confidence: 0.564
Conclusion #4:
if people buy milk they will also buy banana
 - Support: 27
 - Confidence: 0.519
Conclusion #5:
if people buy cheese they will also buy banana
 - Support: 20
 - Confidence: 0.513


In [90]:
#classification example ---- iris (inside the scikit-learn database)
from sklearn.datasets import load_iris
dataset = load_iris()
x = dataset.data
y = dataset.target

In [91]:
#check the description of the iris dataset
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========